const ASANA_TEAM_PROJECT_GID = '1200076563390729';
const PROJECT_ID = '3138d895-6368-4122-9805-5c55ffc2f93d';

module.exports = {
    up: async (queryInterface) => {
        return queryInterface.bulkInsert('Task', [
            // CUSTOM_FIELD GID (ASANA_CUSTOMER_APPROVAL_FIELD): 1199951165136342
            // CUSTOM_FIELD GID (ASANA_TEAM_PROJECT_SECTION_REVISION): 1200076563390739
            {
                Id: '9703bdb3-57a0-4af3-994c-21b56a309465',
                ProjectId: PROJECT_ID,
                AsanaGid: '1200240775499449',
                Name: 'Anchor Text Analysis Underway',
                DueDate: '2021-04-21 00:00:00',
                AssignedToCustomer: false,
                NeedsApproval: false,
                Completed: true,
                Revision: true,
                AsanaDeliverableTypeId: 8,
                Note: null,
                Done: false,
                AsanaTeamProjectGid: ASANA_TEAM_PROJECT_GID,
            }, {
                Id: '37c76f9c-d249-436c-844b-04ae91da0bb1',
                ProjectId: PROJECT_ID,
                AsanaGid: '1200240775255154',
                Name: 'Plastic Materials - Keyword Research',
                DueDate: '2021-04-09 00:00:00',
                AssignedToCustomer: false,
                NeedsApproval: false,
                Completed: false,
                Revision: false,
                AsanaDeliverableTypeId: 1,
                Note: null,
                Done: false,
                AsanaTeamProjectGid: ASANA_TEAM_PROJECT_GID,
            }, {
                Id: 'b1a6b040-e443-4dbf-b42f-a3d3a165403e',
                ProjectId: PROJECT_ID,
                AsanaGid: '1200240775397559',
                Name: 'Technical Battle Audit Underway',
                DueDate: '2021-04-19 00:00:00',
                AssignedToCustomer: false,
                NeedsApproval: false,
                Completed: false,
                Revision: false,
                AsanaDeliverableTypeId: 2,
                Note: null,
                Done: false,
                AsanaTeamProjectGid: ASANA_TEAM_PROJECT_GID,
            }, {
                Id: 'd49f6178-f65d-4700-ac00-29ceca9be585',
                ProjectId: PROJECT_ID,
                AsanaGid: '1200240775634490',
                Name: 'MetaData Optimizations Underway',
                DueDate: '2021-04-09 00:00:00',
                AssignedToCustomer: false,
                NeedsApproval: false,
                Completed: false,
                Revision: false,
                AsanaDeliverableTypeId: 5,
                Note: null,
                Done: false,
                AsanaTeamProjectGid: ASANA_TEAM_PROJECT_GID,
            }, {
                Id: 'f9f291e8-97cf-4170-85cd-627383daffdf',
                ProjectId: PROJECT_ID,
                AsanaGid: '1200240775679796',
                Name: 'Manual Link Disavow Underway',
                DueDate: '2021-04-12 00:00:00',
                AssignedToCustomer: false,
                NeedsApproval: false,
                Completed: false,
                Revision: false,
                AsanaDeliverableTypeId: 7,
                Note: null,
                Done: false,
                AsanaTeamProjectGid: ASANA_TEAM_PROJECT_GID,
            }, {
                Id: 'b0825715-afc4-470e-8a98-309cf9f6dd74',
                ProjectId: PROJECT_ID,
                AsanaGid: '1200240775714251',
                Name: 'Manual Link Disavow Complete',
                DueDate: '2021-04-07 00:00:00',
                AssignedToCustomer: false,
                NeedsApproval: false,
                Completed: false,
                Revision: false,
                AsanaDeliverableTypeId: 7,
                Note: null,
                Done: false,
                AsanaTeamProjectGid: ASANA_TEAM_PROJECT_GID,
            }, {
                Id: '64f7ca13-d0c2-49bd-a243-c1231f9fdfe0',
                ProjectId: PROJECT_ID,
                AsanaGid: '1200240775913352',
                Name: 'Task to test customer approval',
                DueDate: null,
                AssignedToCustomer: true,
                NeedsApproval: false,
                Completed: false,
                Revision: false,
                AsanaDeliverableTypeId: 1,
                Note: 'test notes',
                Done: false,
                AsanaTeamProjectGid: ASANA_TEAM_PROJECT_GID,
            }, {
                Id: 'f5c846ff-194c-4b94-8b62-28b34790fe38',
                ProjectId: PROJECT_ID,
                AsanaGid: '1200240775202329',
                Name: 'Plastic Materials - 10 x Keyword Jacking ',
                DueDate: '2021-04-21 00:00:00',
                AssignedToCustomer: false,
                NeedsApproval: false,
                Completed: true,
                Revision: false,
                AsanaDeliverableTypeId: null,
                Note: null,
                Done: true,
                AsanaTeamProjectGid: ASANA_TEAM_PROJECT_GID,
            },
        ], {});
    },

    down: async (queryInterface) => {
        return queryInterface.bulkDelete('Task', null, {});
    },
};
